### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [BradKuhn/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by BradKuhn** [comment]
I added the code below to application.html.erb that I found on Drupal.org while researching the topic. Viewing it before and after on my phone makes it appear to have fixed the problem.

<meta name="viewport" content="width=device-width, initial-scale=1" />

**Comment by MarcoMorawec** [comment]
@BradKuhn :+1: 

Make sure you close the issue now that you've solved it :)
