### ISSUE TITLE
Fixing the Footer

### ISSUE THREAD

**Issue by MarcoMorawec** [BradKuhn/Splurty#3]
Right now the footer doesn't seem to right-align properly. Take a look at the wireframes again and see if you can align the text in the right-hand side of the footer more towards the right

Here's what I'm seeing:

![screen shot 2015-06-18 at 10 39 04 am](https://cloud.githubusercontent.com/assets/1474717/8233932/00fc36c4-15a7-11e5-8b82-534136ded792.png)

**Comment by BradKuhn** [comment]
I fixed this by adding the following to master.css.scss. Resizing the window to be very narrow makes it align stacked to the left as it should.

.footer-blurb {
    text-align: right;
}
